### ISSUE TITLE
Please add LICENSE file

### ISSUE THREAD

**Issue by joshgoebel** [FreddieRidell/wren-tempo#1]
Trying to figure out if this might be appropriate to include in my `wren-console` and `wren-essentials` projects.  Date/Time handling seems something we really need to mature the CLI experience.

- https://github.com/joshgoebel/wren-console
- https://github.com/joshgoebel/wren-essentials/issues/6

**Comment by FreddieRidell** [comment]
Hey, I'd strongly suggest you fork this repo, I don't think my library is good enough to depend on, and I unfortunatly don't have the time to maintain it.
Best of luck :)

**Comment by joshgoebel** [comment]
> I don't think my library is good enough to depend on

Oh I wouldn't use it as it, but it might serve as a start/foundation.  Obviously the actual leap year code would need to be improved and a lot of tests would need to be added... I'd be happy to fork it, but could you drop a LICENSE so I know what my rights are with regard to using your code?  that's why I was asking.

**Comment by FreddieRidell** [comment]
ahh, cool, sure
